inputs:
  repo-dir:
    description: 'Directory of the git repo.'
    required: true
  branch:
    description: 'Branch for the repo to track.'
    required: true
    default: 'main'

runs:
  using: "composite"
  steps:
  - name: git status (pre-check)
    working-directory: ${{ inputs.repo-dir }}
    shell: pwsh
    run: |
      git status
      git rev-parse HEAD

  - name: git fetch
    working-directory: ${{ inputs.repo-dir }}
    shell: pwsh
    run: git fetch

  # Ensures the repository is not in detached HEAD state
  - name: git switch to `${{ inputs.branch }}`
    working-directory: ${{ inputs.repo-dir }}
    shell: pwsh
    run: git switch -C "${{ inputs.branch }}"

  - name: git hard reset to `${{ inputs.branch }}`
    working-directory: ${{ inputs.repo-dir }}
    shell: pwsh
    run: git reset --hard "origin/${{ inputs.branch }}"

  - name: git pull
    working-directory: ${{ inputs.repo-dir }}
    shell: pwsh
    run: git pull

  - name: git status (post-check)
    working-directory: ${{ inputs.repo-dir }}
    shell: pwsh
    run: |
      git status
      git rev-parse HEAD
