inputs:
  repo-dir:
    description: 'Directory of the target git repo.'
    required: true
  branch:
    description: 'Branch to commit and push.'
    required: true

runs:
  using: "composite"
  steps:
  - name: git config user name
    working-directory: ${{ inputs.repo-dir }}
    shell: pwsh
    run: git config user.name "RaenonX (Auto Datamine)"

  - name: git add all
    working-directory: ${{ inputs.repo-dir }}
    shell: pwsh
    run: |
      Write-Host "git add all at ${{ inputs.repo-dir }}"
      git add .

  - name: git commit
    working-directory: ${{ inputs.repo-dir }}
    shell: pwsh
    run: |
      Write-Host "git commit at ${{ inputs.repo-dir }}"
      
      $FileDiff = $(git status --porcelain)
      if ($FileDiff) {
        Write-Host $FileDiff
        git commit -m "Updated by RaenonX-PokemonTCGP/pokemon-tcgp-aladin-index@${{ github.sha }}"
      } else {
        Write-Host "Nothing to commit"
      }

  - name: git pull
    working-directory: ${{ inputs.repo-dir }}
    shell: pwsh
    run: |
      Write-Host "git pull at ${{ inputs.repo-dir }}"
      
      # Make sure the history is linear
      git pull --rebase --autostash

  - name: git push
    working-directory: ${{ inputs.repo-dir }}
    shell: pwsh
    run: |
      Write-Host "git push at ${{ inputs.repo-dir }}"
      
      $RemoteDiff = $(git log origin/main..main)
      if ($RemoteDiff) {
        Write-Host $RemoteDiff
        git push
      } else {
        Write-Host "Nothing to push"
      }
